version: '3'

services:
  web:
    build: ./apps/client
    ports:
      - '3000:3000'
    volumes:
      - .:/code
    environment:
      - API_URL=http://server:5000
    depends_on:
      - server

  server:
    build: ./apps/server
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
